### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_bnf')

### ISSUE THREAD

**Issue by l-arkadiy-l** [MeteoraAg/dlmm-sdk#117]
When I cloned the repo and started to get up python client server I have got this error after make "npm start-server" command. More exactly when I visited the localhost. I have saw this on localhost:

TypeError: Cannot read properties of undefined (reading '_bnf')
    at isPublicKeyData (/Users/a1234/PycharmProjects/crypto_defi/dlmm-sdk-main/ts-client/node_modules/@solana/web3.js/lib/index.cjs.js:147:16)
    at new PublicKey (/Users/a1234/PycharmProjects/crypto_defi/dlmm-sdk-main/ts-client/node_modules/@solana/web3.js/lib/index.cjs.js:165:9)
    at /Users/a1234/PycharmProjects/crypto_defi/dlmm-sdk-main/ts-client/dist/src/server/index.js:17:16
    at Layer.handle [as handle_request] (/Users/a1234/PycharmProjects/crypto_defi/dlmm-sdk-main/ts-client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/a1234/PycharmProjects/crypto_defi/dlmm-sdk-main/ts-client/node_modules/express/lib/router/index.js:328:13)
    at /Users/a1234/PycharmProjects/crypto_defi/dlmm-sdk-main/ts-client/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/a1234/PycharmProjects/crypto_defi/dlmm-sdk-main/ts-client/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/a1234/PycharmProjects/crypto_defi/dlmm-sdk-main/ts-client/node_modules/express/lib/router/index.js:280:10)
    at jsonParser (/Users/a1234/PycharmProjects/crypto_defi/dlmm-sdk-main/ts-client/node_modules/body-parser/lib/types/json.js:113:7)
    at Layer.handle [as handle_request] (/Users/a1234/PycharmProjects/crypto_defi/dlmm-sdk-main/ts-client/node_modules/express/lib/router/layer.js:95:5)

**Comment by ben0x01** [comment]
Can u find how to solve this problem?
